name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the font
      run: make all
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: dist/*